Repository RegioHelden/django-scrubber, pull requests merged in 2025-04, with the labels that each got.

#63 Switch to reusable github workflows
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  .gitignore
  AUTHORS.md
  Dockerfile
  HISTORY.md
  LICENSE
  MANIFEST.in
  README.md
  compose.yaml
  django_scrubber/services/validator.py
  pyproject.toml
  requirements-ci.txt
  requirements-test.txt
  requirements.txt
  setup.py
  tests/settings.py
Labels: enhancement

#65 Add support for django 5.2
  .github/workflows/workflow.yaml
  pyproject.toml
Labels: enhancement

#66 Release v4.2.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#67 Remove unused bumpversion config
  django_scrubber/__init__.py
  pyproject.toml
Labels: skip-changelog

#69 Pin reusable workflow release
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
Labels: skip-changelog

#70 Move project version to standalone file
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  pyproject.toml
  version
Labels: skip-changelog

#72 Set python min version for modulesync
  .sync.yml
Labels: infrastucture

#75 Updates from modulesync
  .github/dependabot.yml
Labels: infrastucture

#76 Add supported python versions to sync config
  .sync.yml
Labels: infrastucture

#77 Updates from modulesync
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#79 Updates from modulesync
  .devcontainer/devcontainer.json
  pyproject.toml
Labels: infrastucture

#80 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#81 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  Dockerfile
Labels: infrastucture

#82 Updates from modulesync
  compose.yaml
  pyproject.toml
Labels: infrastucture

#83 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#84 Updates from modulesync
  Dockerfile
Labels: infrastucture
