Repository RegioHelden/django-scrubber, pull requests merged in 2025-06, with the labels that each got.

#100 Fix strict mode test
  django_scrubber/tests/test_scrub_data.py
Labels: bug

#107 Updates ruff VSCode integration to 2025.24.0
  .devcontainer/devcontainer.json
Labels: infrastucture

#111 Set changelog start to last release before reusable workflows
  .github/workflows/open-release-pr.yaml
Labels: infrastructure

#112 Add changelog begin tag to sync yaml for modulesync
  .sync.yml
Labels: infrastructure

#117 Release signing fix on reusable actions
  .github/workflows/build-and-publish.yaml
Labels: skip-changelog

#118 Release v5.2.0
  CHANGELOG.md
Labels: skip-changelog

#122 Update uv to 0.7.15
  Dockerfile
Labels: infrastucture

#123 Release v5.3.0
  CHANGELOG.md
  version
Labels: skip-changelog

#124 Update uv to 0.7.17
  Dockerfile
Labels: infrastucture
